# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.BooleanField(default=False)),
                ('tipo', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
