# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='voletos',
            new_name='voleto',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='posi',
        ),
        migrations.AddField(
            model_name='voleto',
            name='posi',
            field=models.CharField(choices=[(b'V', b'VIP'), (b'A', b'alto'), (b'M', b'medio'), (b'P', b'platino')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
