# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20171116_2124'),
        ('user', '0002_auto_20171116_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voleto',
            name='use',
        ),
        migrations.AddField(
            model_name='voleto',
            name='use',
            field=models.ManyToManyField(null=True, to='log.UserModel'),
        ),
    ]
