# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171120_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voleto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
